apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: shopping-mall
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:19090
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:13100
