apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-frontend
  namespace: shopping-mall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-frontend
  template:
    metadata:
      labels:
        app: shop-frontend
    spec:
      containers:
        - name: shop-frontend
          image: shopping-mall-shop-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: shop-frontend
  namespace: shopping-mall
spec:
  selector:
    app: shop-frontend
  ports:
    - port: 13000
      targetPort: 3000
